version: '3'
services:
  ovpnadmin:
    build: .
    ports:
     - "443:443"
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: example
